project:
  type: website
  output-dir: docs

website:
  title: "Brassicas"
  navbar:
    background: "#43A047"
    border: true
    left:
    - recetas.qmd
    right: 
    - icon: facebook
      href: https://www.facebook.com/Brassicas20
    - icon: instagram
      href: https://www.instagram.com/brassicas_/
    
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

